### ISSUE TITLE
Update dependencies, npm install fails with node v13.3.0

### ISSUE THREAD

**Issue by iby** [oktadev/okta-node-express-typescript-vue-example#4]
It starts with the following and the list goes on and on:

```log
> deasync@0.1.13 install /Users/ianbytchek/Downloads/okta-node-express-typescript-vue-example-master/node_modules/deasync
> node ./build.js

  CXX(target) Release/obj.target/deasync/src/deasync.o
In file included from ../src/deasync.cc:3:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ianbytchek/Library/Caches/node-gyp/13.3.0/include/node/v8.h:2762:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
```

Looks like [deasync v0.1.16](https://github.com/abbr/deasync/releases/tag/v0.1.16) takes care of the latest node, but I can't see in the dependency tree what module pulls it.

**Comment by tmatera** [comment]
Hi, did you solve the problem somehow? I'm currently facing the same issue..

**Comment by ianbytchek** [comment]
Don't think I did. My overall discovery while getting up to speed with Vue was that there is a lot of really cool examples, like this one, and majority of them are outdated, some beyond the point of building and running. 

I hated it to guts, but forced myself to move away from managing webpacking of the app in favor of the Vue CLI, which uses it behind the scenes anyway. What's funny, I also managed to get it working with webpack, but the build time and size were significantly longer and larger compared to Vue CLI. I obviously did something wrong, but was left with feeling that the invested time and further maintenance are not worse it.

**Comment by w495** [comment]
+1

**Comment by alisaduncan** [comment]
Thanks for filing this and alerting us to the troubles you faced. The post & code sample has been updated with new deps and works on Node v14.18. I agree with you, using Vue CLI will be the way to go going forward. 

Closing as #11 gets the app working again.
